light = int(input("Показания за свет: "))
gaz = int(input("Показания за газ: "))
home = int(input("Наём жилья: "))
cool_and_heat_water = int(input("Холодная и горячая вода: "))
trash = int(input("Вывоз мусора: "))
heating = int(input("Горячая вода и отопление: "))
apartment = int(input("Общее за квартиру: "))
intercom = int(input("Домофон"))
my_pay = ((trash/2) + (heating/2) + (apartment/2) + (home/2) + (intercom/2))
print(f"Моя доля: {my_pay}")
brother_pay = (light + gaz + (home/2) + cool_and_heat_water + (trash/2) + (heating/2) + (apartment/2) + (intercom/2))
print(f"Доля брата:  {brother_pay}")
